default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: detect-private-key

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.6.0
    hooks:
      - id: pycln
        name: prune imports
        args: [--expand-stars]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.14
    hooks:
      - id: ruff
        name: lint and fix
        args: [--fix]
      - id: ruff-format
        name: format code

  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        name: format markdown
        additional_dependencies:
          - mdformat-gfm
          - mdformat_frontmatter
        exclude: CHANGELOG.md

  - repo: https://github.com/crate-ci/typos
    rev: v1
    hooks:
      - id: typos
